name: BattleCTF
authors: [AlexTheAussie]
version: 0.1
main: org.alexdev.battlectf.BattleCTF

commands:
  battlectf:
    description: The core plugin for handling many BattleCTF commands
    aliases: [ctf]
    usage: |
      /ctf [arguments]
    permission: myplugin.admin

permissions:
  myplugin.use:
    description: use myplugin
    default: true
  myplugin.admin:
    description: myplugin admin features
    default: op