package org.alexdev.battlectf.managers.arena;

public enum ArenaFlags {
    ALLOW_BLOCK_BREAKING,
    ALLOW_BLOCK_PLACING,
    ALLOW_MOB_SPAWNING,
    ALLOW_ANIMAL_SPAWNING,
    ALLOW_EXPLOSIONS,
    ALLOW_LAVA_FLOW,
    ALLOW_WATER_FLOW,
    ALLOW_LEAF_DECAY,
    ALLOW_FIRE_SPREAD,
    ALLOW_FIRE_IGNITE,
    ALLOW_FIRE_BURN,
    ALLOW_MUSHROOM_SPREAD,
    ALLOW_VINE_SPREAD,
    ALLOW_GRASS_SPREAD
}
