package org.alexdev.battlectf.managers.arena;

public enum ArenaFlags {
    ALLOW_BLOCK_BREAKING,
    ALLOW_BLOCK_PLACING,
    ALLOW_MOB_SPAWNING,
    ALLOW_ANIMAL_SPAWNING,
    ALLOW_EXPLOSIONS,
    ALLOW_LAVA_FLOW,
    ALLOW_WATER_FLOW,
    ALLOW_LEAF_DECAY,
    ALLOW_FIRE_SPREAD,
    ALLOW_HUNGER_DEPLETE,
    ALLOW_GRASS_SPREAD,
    ALLOW_GRASS_DEATH
}
